# Docker desarrollo
FROM node:14.3.0

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

COPY . ./

# Puerto cliente api
EXPOSE 4200

CMD ["npm", "start"]
